apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: food-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: production-ready-quickbite-cloud-native-3-tier-food-ordering-platform-backend:latest #mohammadkasim/quickbite-backend:latest
          imagePullPolicy: IfNotPresent #Always

          ports:
            - containerPort: 5001

          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_URI

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          livenessProbe:
            httpGet:
              path: /
              port: 5001
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 5
