apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: food-app
type: Opaque
stringData:
  MONGO_URI: mongodb://admin:password123@mongodb:27017/?authSource=admin #mongodb://admin:password123@mongodb:27017/?authSource=admin
#bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkMTIzQG1vbmdvZGI6MjcwMTcvP2F1dGhTb3VyY2U9YWRtaW4= 
#bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkMTIzQG1vbmdvZGI6MjcwMTc=
