services:
  mongodb:
    image: mongo:7.0
    container_name: quickbite_db
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db

  backend:
    image: mohammadkasim/food-app-backend:${IMAGE_TAG:-latest}
    container_name: quickbite_backend
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      MONGO_URI: mongodb://mongodb:27017/foodiehub
      PORT: 5001
    depends_on:
      - mongodb

  frontend:
    image: mohammadkasim/food-app-frontend:${IMAGE_TAG:-latest}
    container_name: quickbite_frontend
    restart: unless-stopped
    ports:
      - "8000:80"
    depends_on:
      - backend

volumes:
  mongodb_data:
