apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: food-app
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: admin #YWRtaW4=        # "admin" encoded in base64
  MONGO_INITDB_ROOT_PASSWORD: password1234 #cGFzc3dvcmQxMjM= #bXktcGFzc3dvcmQ=  # "my-password" encoded in base64
