name: CI Pipeline
on:
  push:
    branches: feature/ci-cd

concurrency:
  group: quickbite-ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: 
  contents: read


 ## ********* BAckend CI ***************##
jobs:
  backend-ci:
    name: Backend CI
    runs-on: ubuntu-latest

    defaults:
      run: 
        working-directory: backend
    
    steps:
      - name: Checkout Repositroy
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: node --check server.js
        continue-on-error: false

    ## *****  Docker Build ***** ##
  docker:
    name: Docker Build
    runs-on: ubuntu-latest

    needs:
      - backend-ci

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Docker Compose
        run: docker compose config

      - name: Set image tag
        run: |
         echo "IMAGE_TAG=${GITHUB_SHA::12}" >> "$GITHUB_ENV"    

      - name: Build backend image
        run: | 
          docker build \
          --file ./Dockerfile.backend \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/quickbite-backend:latest \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/quickbite-backend:${IMAGE_TAG} \
          .

      - name: Build frontend image
        run: | 
          docker build \
          --file ./Dockerfile.frontend \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/quickbite-backend:latest \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/quickbite-backend:${IMAGE_TAG} \
          .
      - name: Check Docker images
        run: docker images
        
## ***** Security Scan ***** ##
  security:
    name: Container Security Scan
    runs-on: ubuntu-latest

    needs:
      - docker

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build backend image
        run: |
          docker build \
            -f Dockerfile.backend \
            -t quickbite-backend:scan .

      - name: Build frontend image
        run: |
          docker build \
            -f Dockerfile.frontend \
            -t quickbite-frontend:scan .

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.3

      - name: Scan backend image
        run: |
          trivy image \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            quickbite-backend:scan

      - name: Scan frontend image
        run: |
          trivy image \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            quickbite-frontend:scan